spring:
  application:
    name: service1
  zipkin:
    base-url: http://localhost:8080

server:
  port: 8081

---

spring:
  profiles: docker
  zipkin:
    base-url: http://zipkin-server:8080

server:
  port: 8080