version: "2.2"

networks:
  zipkin:
    external: 
      name: zipkin

services:
  zipkin-server:
    restart: always
    mem_limit: 512m
    build: zipkin-server
    image: zipkin/server
    container_name: zipkin-server
    ports:
      - 9411:8080
    networks:
      - zipkin

  zipkin-client-service1:
    restart: always
    mem_limit: 512m
    build: zipkin-client-service1
    image: zipkin/client-service1
    container_name: zipkin-client-service1
    ports:
      - 8081:8080
    networks:
      - zipkin

  zipkin-client-service2:
    restart: always
    mem_limit: 512m
    build: zipkin-client-service2
    image: zipkin/client-service2
    container_name: zipkin-client-service2
    ports:
      - 8082:8080
    networks:
      - zipkin